Repository freebsd/freebsd-src, pull requests merged in 2024-05, with the labels that each got.

#1193 packages: add package for NTP
  libexec/rc/rc.d/Makefile
  release/packages/Makefile.package
  usr.sbin/ntp/doc/Makefile
  usr.sbin/ntp/doc/drivers/Makefile
  usr.sbin/ntp/doc/drivers/icons/Makefile
  usr.sbin/ntp/doc/drivers/scripts/Makefile
  usr.sbin/ntp/doc/hints/Makefile
  usr.sbin/ntp/doc/icons/Makefile
  usr.sbin/ntp/doc/pic/Makefile
  usr.sbin/ntp/doc/scripts/Makefile
  usr.sbin/ntp/libntp/Makefile
  usr.sbin/ntp/libntpevent/Makefile
  usr.sbin/ntp/libopts/Makefile
  usr.sbin/ntp/libparse/Makefile
  usr.sbin/ntp/ntp-keygen/Makefile
  usr.sbin/ntp/ntpd/Makefile
  usr.sbin/ntp/ntpdate/Makefile
  usr.sbin/ntp/ntpdc/Makefile
  usr.sbin/ntp/ntpq/Makefile
  usr.sbin/ntp/ntptime/Makefile
  usr.sbin/ntp/sntp/Makefile
  usr.sbin/periodic/etc/daily/Makefile
Labels: changes-required

#1192 intro.2: add syscall.h to synopsis & mention emfile vars
  lib/libsys/intro.2
Labels: needs-review

#1215 arp.8: don't document a syntax that doesn't exist
  usr.sbin/arp/arp.8
Labels: needs-review

#1195 sysexits: tidy deprecated header and manual
  include/sysexits.h
  share/man/man3/sysexits.3
Labels: needs-review

#1210 mdconfig: Print options when listing devices
  sbin/mdconfig/mdconfig.c
Labels: changes-required

#1225 kern/intr: remove support for passing trap frame as argument
  sys/kern/kern_intr.c
Labels: ready

#1161 /bin/rmdir: Exit with status 2 for invalid arguments
  bin/rmdir/rmdir.1
  bin/rmdir/rmdir.c
  bin/rmdir/tests/rmdir_test.sh
Labels: ready

#1223 netstat(1): increase width of Netif column
  usr.bin/netstat/nhops.c
  usr.bin/netstat/route.c
Labels: ready

#1236 sys/modules/dpdk_lpm4: do not build without INET
  sys/modules/Makefile
Labels: ready

#1238 cp: avoid a resource leak
  bin/cp/utils.c
Labels: needs-review

#1220 arp(8): allow -i with -s
  usr.sbin/arp/arp.c
Labels: needs-review

#1228 Remove COMPAT_FREEBSD4/5/6/7/9 from MINIMAL and FIRECRACKER kernel configurations
  sys/amd64/conf/FIRECRACKER
  sys/amd64/conf/MINIMAL
  sys/i386/conf/MINIMAL
Labels: needs-review

#1245 fix C++ compile errors (FreeBSD-current)
  sys/netlink/netlink_snl.h
  sys/netlink/netlink_snl_route.h
  sys/netlink/netlink_snl_route_parsers.h
Labels: changes-required

#1260 linux: implement PR_CHILD_SET_SUBREAPER
  sys/compat/linux/linux_misc.c
  sys/compat/linux/linux_misc.h
Labels: needs-review

#1258 rc: improve NAME_setup handling
  libexec/rc/rc.subr
  share/man/man8/rc.subr.8
Labels: needs-review

#1261 export $autoboot var when running from $boottrace_cmd to fix root check root check if boottrace is enabled
  libexec/rc/rc.subr
Labels: needs-review, special

#1266 bluetooth/fwdownloader mans: terse descriptions
  usr.sbin/bluetooth/ath3kfw/ath3kfw.8
  usr.sbin/bluetooth/bcmfw/bcmfw.8
  usr.sbin/bluetooth/iwmbtfw/iwmbtfw.8
Labels: changes-required
